name: Run performance benchmarks on different pieces

on:
  push

jobs:
  test-binaries:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 50
          fetch-tags: true

      # TODO abstract
      - name: Download shell-language
        run: |
          mkdir bin
          gh release download -R kaleidawave/experiments assets -p shell-language -D bin
          ls -R .
          chmod +x ./bin/shell-language
          echo "$(pwd)/bin" >> "$GITHUB_PATH"
        env:
          GH_TOKEN: ${{ github.token }}

      - uses: brndnmtthws/rust-action-cargo-binstall@v1
        with:
          packages: hyperfine

      - name: Install valgrind (and callgrind)
        run: sudo apt-get install valgrind

      - name: Get file
        run: curl -sS $URL > out.html
        env:
          URL: "https://gist.githubusercontent.com/kaleidawave/643854be768e5c11196247cde8daa1d0/raw/2da32a579ab92721d277e1ee8c8d5cf3f4552ec7/bbc.html"
      
      - name: Build binaries
        run: |
          for git tag --list "performance/*" each
            echo run git checkout tags/$tag --force
            let name = replace $tag "/" "-"
            echo "Building parse-$name from $tag"
            echo run cargo build --release --example parse
            # echo run stat ./target/release/examples/parse
            move ./target/release/examples/parse "binaries/parse-$name"
        shell: shell-language {0}

      - name: Run binaries
        continue-on-error: true
        run: |
          for files "binaries/*" each
            echo "Running $file"
            let out = run "./$file" $INPUT --check
            # echo run stat "./$file"
            echo $out
        shell: shell-language {0}
        env:
          INPUT: "out.html"

      - name: Compare binaries
        run: |
          let binaries = files "binaries/*"
          let binaries = replace $binaries "\n" ","
          # echo "binaries: $binaries"
          let output = run hyperfine -i -L binary $binaries './{binary} $INPUT --check'
          let to = env GITHUB_STEP_SUMMARY
          append $to "# Performance results"
          append $to "```shell\n$output\n```"
        shell: shell-language {0}
        env:
          INPUT: "out.html"

      - name: Memory usage
        continue-on-error: true
        run: |
          let to = env GITHUB_STEP_SUMMARY
          append $to "## Memory usage"
          for files "binaries/*" each
            echo "Running $file"
            let output = run valgrind $file $INPUT --check --merge-stdout-and-stderr
            let allocated = regexp $output "(?<bytes>[\\d,]+) bytes allocated" extract bytes
            let allocated = replace $allocated "," ""
            let allocated = format_number $allocated
            append $to "- `$file`: `$allocated` allocated"
        shell: shell-language {0}
        env:
          INPUT: "out.html"

      - name: Instruction count
        continue-on-error: true
        run: |
          let to = env GITHUB_STEP_SUMMARY
          append $to "## Instruction count"
          for files "binaries/*" each
            echo "Running $file"
            let output = run valgrind --tool=callgrind $file $INPUT --check --merge-stdout-and-stderr
            let instructions = regexp $output "Collected : (?<name>\\d+?)\\b" extract name
            echo "instructions='$instructions'"
            # let instructions = format_number $instructions
            # append $to "- `$file`: `$instructions` instructions"
        shell: shell-language {0}
        env:
          INPUT: "out.html"
