name: Run performance benchmarks on different pieces

on:
  push

jobs:
  test-binaries:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 50
          fetch-tags: true

      # TODO abstract
      - name: Download shell-language
        run: |
          mkdir bin
          gh release download -R kaleidawave/experiments assets -p shell-language -D bin
          ls -R .
          chmod +x ./bin/shell-language
          echo "$(pwd)/bin" >> "$GITHUB_PATH"
        env:
          GH_TOKEN: ${{ github.token }}

      - uses: brndnmtthws/rust-action-cargo-binstall@v1
        with:
          packages: hyperfine

      - name: Get file
        run: curl -sS $URL > out.html
        env:
          URL: "https://www.bbc.co.uk/news"

      - name: (temp) check things
        run: git log
      
      - name: Build binaries
        run: |
          for tags "performance/*" each
            echo "Checking out $tag"
            run git checkout tags/$tag
            let status = run git log -n 1
            echo $status
            run cargo build --release --example parse
            let name = replace $tag "/" "-"
            echo "Building parse-$name from $tag"
            move ./target/release/examples/parse "binaries/parse-$name"
        shell: shell-language {0}

      - name: (temp) check things
        run: ls -R .

      - name: (temp) check binary
        continue-on-error: true
        run: ./binaries/parse-performance-base1 out.html --check

      - name: Run binaries
        continue-on-error: true
        run: |
          for files "binaries/*" each
            let out = run "./$file" $INPUT --check
            echo "Running $file"
            echo $out
        shell: shell-language {0}
        env:
          INPUT: "out.html"

      - name: Compare binaries
        run: |
          let binaries = files "binaries/*"
          let binaries = replace $binaries "\n" ","
          echo $binaries
          let output = run hyperfine -i -L binary $binaries './{binary} $INPUT --check'
          let to = env GITHUB_STEP_SUMMARY
          write $to "```\n$output```"
        shell: shell-language {0}
        env:
          INPUT: "out.html"